# Generated by Django 4.2.1 on 2023-05-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mkbten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos_code', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnos_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
