# Generated by Django 4.2.1 on 2023-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mkbten'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos_code', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnos', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mkbten',
            old_name='diagnos_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mkbten',
            old_name='diagnos_name',
            new_name='name',
        ),
    ]
