# Generated by Django 4.2.1 on 2023-05-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diagnos_rename_diagnos_code_mkbten_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naznachenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos_code', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnos', models.JSONField(blank=True, default=dict, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='diagnos',
        ),
    ]
