# Generated by Django 4.2.1 on 2023-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_naznachenie_diagnos_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkbten',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
